name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 13.49.243.67
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/portfolio"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 13.49.243.67
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/portfolio
          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -a -q) || true
          sudo docker build -t my-portfolio .
          sudo docker run -d -p 80:4173 my-portfolio
